locale: "en-US"
site_theme: "default"
title: "Junteng Liu"
title_separator: "-"
name: "Junteng Liu"
description: "First-year PhD candidate at HKUST NLP Group"
url: "https://atool3800-stack.github.io"
baseurl: "/LJT-Homepage"
repository: "atool3800-stack/LJT-Homepage"

author:
  name: "Junteng Liu"
  bio: "First-year PhD candidate at HKUST NLP Group"
  employer: "HKUST NLP Group"
  email: "jliugi@connect.ust.hk"
  googlescholar: "https://scholar.google.com/citations?hl=en\u0026user=tbK9jl4AAAAJ\u0026view_op=list_works\u0026sortby=pubdate"
  github: "Vicent0205"
  twitter: "junteng88716710"

breadcrumbs: false
future: true
read_more: "disabled"
talkmap_link: false
comments:
  provider:
atom_feed:
  hide: true

include:
  - .htaccess
  - _pages
  - files
exclude:
  - ".bundle"
  - ".github"
  - "node_modules"
  - "vendor"
  - "Dockerfile"
  - "Gemfile"
  - "LICENSE"
  - "README.md"

collections:
  teaching:
    output: false
  publications:
    output: false
  portfolio:
    output: false
  talks:
    output: false

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
timezone: Etc/UTC
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
plugins: []
compress_html:
  clippings: all
  ignore:
    envs: development
